### PR TITLE
chore: Add workflows

### LINKED ISSUE #6: Add workflows
## Summary

What:

Add the following workflows:

* master - running tests and linting
* bumper - updating dependencies

Why:

To ensure code works and the repository is in working order and up to date

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Create two new workflows (master, bumper), very similar to how the other repos have them

### PR DESCRIPTION
**Pull request by ebebbington**
Fixes #6 

## Summary

* Adds useful workflows for the org project and others

### CODE REVIEW

**Comment by ebebbington** [comment]
ehhh @crookse heelp me

**Comment by crookse** [comment]
got you fam

**Comment by crookse** [comment]
we good now

**Comment by ebebbington** [comment]
lgtm

**Pull request merged**
