### PR TITLE
Fix OPTIONS

### PR DESCRIPTION
**Pull request by saragee3**
## Purpose

This was not a part of any issue. Options on help menu should pertain to top level options. It doesn't really make sense the way it is now.

### CODE REVIEW

**Comment by saragee3** [comment]
is there an easy way to test this or should i just point my current working `deno-drash` branch to this local `cli_service.ts`. Also feel like this `cli_service.ts` can use some fixing up in general... will make another ticket after some investigation.

**Comment by crookse** [comment]
there aren't any tests for this service in this repo yet. this makes sense, but how would the user use options?

```
command [options] [subcommand]?
```

or

```
command [subcommand] something else [options]
```

both?

i ask because there's a level of maintenance that come with these and i prefer we go the easy route. that's just me though

**Comment by crookse** [comment]
btw i went with `command [subcommand] [options]` because it was easier to maintain in the code. if you find a solution that works even better, i'm all for it. rhum's cli has `--filter-test-case` and `--filter-test-suite` options for the `test` subcommand. breno stated that users should be allowed to place options anywhere, but parsing a command and figuring out where an option is in the command was difficult for me

**Comment by saragee3** [comment]
Going to close this and revisit it later if we so desperately want to change it ;)

**Pull request closed without merging**
