### PR TITLE
Restructure CLI to have recursive help menus

### PR DESCRIPTION
**Pull request by crookse**

### CODE REVIEW

**Review by ebebbington — APPROVED** [review]
LGTM, Nice one! Only thing I’m thinking about is if docblocks would be useful here, and maybe some examples on how to use this new cli service? Not really a big deal tbh tho

**Comment by crookse** [comment]
im missing HELLA doc blocks lmao

**Comment by ebebbington** [comment]
Is it possible to also add some unit tests?

**Comment by crookse** [comment]
oh right. duh. lolzzzzzzzzzzz

**Comment by ebebbington** [comment]
Whats the status of this Line is now a thing?

**Comment by crookse** [comment]
closing. line is a thing now

**Pull request closed without merging**
