### PR TITLE
Updated the 'create command class'

### PR DESCRIPTION
**Pull request by japrozs**
Created a class to register command to the program

### CODE REVIEW

**Comment by saragee3** [comment]
Hi @Japroz-Saini. What's your progress on this? A few issues here:

- we do not use `jest` for testing. or node for that matter. this is a deno app.
- for testing, check out drash's `rhum` in our /tests dir
- as mentioned on the discord channel, this does _not_ solve our issue of nested commands and flexibility. what will be most beneficial at this stage is to write as many tests as you can to check every command permutation 

If you're not working on it, please let us know so we can go ahead and close out this pr. I will be closing out https://github.com/drashland/services/pull/12

thanks!

**Comment by japrozs** [comment]
I am working on it. But as @Guergeiro told me in the discord, it would be best to write it in node and typescript.

**Comment by Guergeiro** [comment]
Hello @Japroz-Saini, the suggestion to use Node came from you, I always said it must be on Deno, but you could provide a Node solution (if possible using TypeScript) as a code snippet, but never as a final product...
This PR doesn't use Deno nor TypeScript, so it would never be merged. It can be used if you want to play around with a possible solution.

**Comment by ebebbington** [comment]
Hi @japrozs, because there has been no activity for nearly 6 months, we're deciding to close this pull request. If you wanted to continue the work, i'd suggest reading the comments left by @saragee3 and @Guergeiro, and open a pull request at https://github.com/drashland/line, as Line is now our official CLI service. Whereas the CLI service service in this repository will soon be removed.

**Pull request closed without merging**
